grafana/shared-workflows

.github/workflows/publish-techdocs.yaml

I want them to be grouped in our secrets list

Rename bucket secret

---

actions/get-vault-secrets/action.yaml

_tedious change_, just noticed it while making some other changes in here, so getting it submitted first

get-vault-secrets: Remove some trailing whitespace errors

---

actions/push-to-gar-docker/action.yaml

${ROOT_REPO} -> ${{ env.ROOT_REPO }}

`push-to-gar` action: Fix `ROOT_REPO` env var

---

.editorconfig
.github/dependabot.yml
.github/workflows/publish-techdocs.yaml
actions/dockerhub-login/README.md
actions/get-vault-secrets/action.yaml

Help editors enforce the same style so we don't have to bother about it in reviews ([ref]).
[ref]: https://editorconfig.org/

Add .editorconfig

---

actions/build-push-to-dockerhub/action.yaml
actions/push-to-gar-docker/action.yaml

- Adding file input for docker build actions
- Updating docker/build-push-action to use the same version across actions
- Updating docker context description

Add docker file option for actions that build docker images

---

actions/build-push-to-dockerhub/action.yaml
actions/push-to-gar-docker/action.yaml

Reverts grafana/shared-workflows#41

Revert "Add docker file option for actions that build docker images"

---

actions/build-push-to-dockerhub/action.yaml
actions/push-to-gar-docker/action.yaml

Second attempt to add docker file variable. I went simpler this time and didn't bother trying to combine context and dockerfile. 
I think this is a simpler and cleaner solution that my previous attempt.

Adding file argument to docker actions

---

CODEOWNERS

add infra-o11y-frontend as a new codeowner

add new codeowner

---

actions/login-to-gar/README.md
actions/login-to-gar/action.yaml

Adds Github action to login to Google Artifact Registry

Github Action: Add `login-to-gar` github action

---

actions/aws-auth/README.md
actions/aws-auth/action.yaml

This creates an action to authenticate to AWS using cognito

feat(actions): Create `aws-auth` composite action

---

actions/aws-auth/README.md

docs(aws-auth action): Add example of IAM role setup

---

actions/push-to-gar-docker/README.md

Fixes README.md, since it's outdated.

`push-to-gar-docker`: Update README.md

---

actions/login-to-gar/README.md

c/p issue - fixing `README.md`

README: Fix `login-to-gar` README

---

actions/login-to-gar/README.md
actions/login-to-gar/action.yaml
actions/push-to-gar-docker/action.yaml

Removes duplication - uses one composite action in another.

`GAR`: Use `login-to-gar` in `push-to-gar-docker`

---

CODEOWNERS
actions/syft-sbom-report/README.md
actions/syft-sbom-report/syft-sbom.yml

Hello!
Quick PR to add an Action to generate an SBOM report. We use this currently for Grafana and Loki. We'll be adding this to more repos soon.

Add SBOM Reporting Action

---

.github/workflows/publish-techdocs.md
.github/workflows/publish-techdocs.yaml
actions/techdocs-rewrite-relative-links/README.md
actions/techdocs-rewrite-relative-links/action.yaml

Pinning will happen in a follow-up PR

publish-techdocs: Add publish input and fix action checkout

---

actions/send-slack-message/README.md

chore: update readme.md

---

actions/setup-conftest/README.md
actions/setup-conftest/action.yaml

title says it, follows the same pattern as `install-argo-cli`.

feat: add setup-conftest action

---

actions/trigger-argo-workflow/action.yaml

fix(trigger-argo-workflow): use setup-argo action

---

actions/setup-argo/action.yaml

fix(setup-argo): less fragile OS/ARCH selection

---

actions/get-vault-secrets/action.yaml

added github oidc token as a header. This allow us to remove IAP proxy from the auth process beacouse we validate the github OIDC token directly.

feat: added github oidc token as a header

---

actions/setup-argo/README.md

Small fix, I did the mistake to copy paste it without having a closer look.

fix: wrong linked action in argo docs

---

actions/lint-pr-title/README.md

Part of: https://github.com/grafana/shared-workflows/issues/574

chore: add release-please block to lint-pr-title

---

.github/workflows/test-setup-jrsonnet.yml
actions/setup-jrsonnet/README.md
actions/setup-jrsonnet/action.yaml
release-please-config.json

I'm using a version of this action in https://github.com/grafana/grafana-crossplane-libsonnet but think it would be good to maintain this as a shared workflow.

feat: introduce setup-jrsonnet action

---

actions/trigger-argo-workflow/cmd/trigger-argo-workflow/argo.go
actions/trigger-argo-workflow/cmd/trigger-argo-workflow/argo_test.go

This fix utilizes the built-in [Permanent](https://pkg.go.dev/github.com/cenkalti/backoff/v4@v4.3.0#Permanent) function to abort the retry logic within `Run()` if a permanent error is returned by `runCmd()`.
Fixes [this](https://github.com/grafana/shared-workflows/issues/69) issue.

fix(trigger-argo-workflow): prevent unnecessary retries if a permanent error is encountered

---

actions/get-vault-secrets/README.md
actions/push-to-gar-docker/README.md
actions/push-to-gcs/README.md
actions/setup-argo/README.md
actions/trigger-argo-workflow/README.md
actions/validate-policy-bot-config/README.md

Addresses [this](https://github.com/grafana/deployment_tools/issues/161757) issue.

feat(docs): added EngHub doc links to corresponding actions readmes

---

.release-please-manifest.json

Config broke after rebasing changes. Need to merge these and rerun some actions.

fix: fix release please manifest broken config json

---

actions/find-pr-for-commit/README.md

Release `find-pr-for-commit` action.

feat: update readme to include new version change

---

actions/push-to-gar-docker/README.md
actions/push-to-gar-docker/action.yaml

Add optional field to specify custom labels that will be passed as args for the build-push-action.

feat(push-to-gar-docker): add custom label input

---

.github/workflows/test-techdocs-rewrite-relative-links.yaml
actions/techdocs-rewrite-relative-links/main.go
actions/techdocs-rewrite-relative-links/main_test.go
actions/trigger-argo-workflow/cmd/trigger-argo-workflow/argo.go
actions/trigger-argo-workflow/cmd/trigger-argo-workflow/argoflags_test.go

This resolves some linting issues in the two Go actions.

fix: fix linting issues

---

release-please-config.json

Adding that action to the release-please configuration will allow that to create new release PRs.

chore: add release setup for remove-checkout-credentials

---

README.md
actions/argo-lint/README.md
actions/aws-auth/README.md
actions/build-push-to-dockerhub/README.md
actions/dependabot-auto-triage/README.md
actions/dockerhub-login/README.md
actions/find-pr-for-commit/README.md
actions/generate-openapi-clients/README.md
actions/get-vault-secrets/README.md
actions/lint-pr-title/README.md
actions/login-to-gar/README.md
actions/login-to-gcs/README.md
actions/push-to-gar-docker/README.md
actions/push-to-gcs/README.md
actions/send-slack-message/README.md
actions/setup-argo/README.md
actions/setup-conftest/README.md
actions/setup-jrsonnet/README.md
actions/validate-policy-bot-config/README.md

Needed after https://github.com/grafana/shared-workflows/pull/1004.
release-please updates only major/minor/patch numbers without caring about the actual tag pattern.

docs: update all readmes to replace hyphen with slash

---

actions/get-latest-workflow-artifact/bun.lock
actions/get-latest-workflow-artifact/package.json
actions/get-latest-workflow-artifact/src/main.ts

... from https://github.com/grafana/shared-workflows/pull/1022

fix(get-latest-workflow-artifact): suggested fixes

---

release-please-config.json

Add create-github-app-token to release please config

fix(create-github-app-token): add create-github-app-token to release please config

---

CODEOWNERS

https://github.com/grafana/shared-workflows/pull/1290#issuecomment-3257490753

chore: add CODEOWNERS for Azure Trusted Signing action

---

.github/workflows/publish-techdocs.yaml

https://github.com/backstage/backstage/blob/master/packages/techdocs-cli/CHANGELOG.md#198

chore: bump @techdocs/cli to 1.9.8
