- CODEOWNERS
@grafana/cloud-release will be the default reviewers of PRs. A team can set themselves/their team to own certain workflows.
> CODEOWNERS: initialize file

- .github/workflows/publish-techdocs.yaml
Setting this pip cache requires a `requirements.txt` file somewhere in the project or the step fails. Remove the `cache` input as not all projects will have a `requirements.txt`.
> fix(publish-techdocs): remove cache from setup-python

- .github/dependabot.yml
- .github/workflows/publish-techdocs.yaml
This add a dependabot workflow that should lead to opening a PR to bump the python workflow that will eventually make this warning go away once merged.
> Bump python action

- .github/workflows/publish-techdocs.yaml
We've just enabled support for this. Use it in downstream consumers -
gets rid of static service account credentials.
> Use workload identity federation instead of static SA credentials

- actions/get-vault-secrets/README.md
- actions/get-vault-secrets/action.yaml
- actions/get-vault-secrets/translate-secrets.bats
- actions/get-vault-secrets/translate-secrets.sh
The benefit of this action are:
- Cuts down secret fetching to a single step/action
- Puts the logic of fetching secrets in a single location. Easier to update and maintain.
> Add action to get secrets from our Vault instance

- actions/push-to-gar-docker/README.md
- actions/push-to-gar-docker/action.yaml
Instead of passing just one docker image, the workflow should be able to push more than one tags for the same image, but also more than one images even if they're different. 
Related PR: https://github.com/grafana/grafana-backstage/pull/148
> GAR: Add option to push multiple tags

- actions/trigger-argo-workflow/action.yaml
If a paremeter has spaces in it, they're being passed separately to the program, like `[--parameter, foo=, bar, baz]` instead of `[--parameter, foo=barbaz]`. This fails to run.
> trigger-argo-workflow: Don't re-split parameters

- actions/push-to-gar-docker/action.yaml
Part of: https://github.com/grafana/deployment_tools/issues/110276
We need this input variable for automating the `github-<REPO_NAME>-<ENV_NAME>@...` service account construction.
Can be either dev/prod, defaults to dev.
Will be revisited - ideally we should just add `dev` or `prod` to the initial GHA caller workflow and everything should be resolved to the appropriate projects and envs.
> OIDC auth: Add `environment` input variable

- actions/push-to-dockerhub/README.md
- actions/push-to-dockerhub/action.yaml
- actions/push-to-gar-docker/README.md
Part of: https://github.com/grafana/deployment_tools/issues/108822
Along with OIDC way of pushing to GAR through GitHub actions, we need a workflow to push Docker images to DockerHub.
We need to make sure that DockerHub will only contain the end-product images (i.e. `grafana/grafana`, `grafana/mimir` etc.) and all the other images which are used for tooling should be pushed to GAR.
The DockerHub credentials are being fetched from vault.
> Dockerhub: Add `push-to-dockerhub` action

- actions/push-to-dockerhub/README.md
- actions/push-to-gar-docker/README.md
- actions/push-to-gar-docker/action.yaml
Instead of having a hardcoded service account, we should have it constructed based on the attributes of the caller repository. 
This way we can make sure that the caller workflow can only push artifacts to the registry it means to, using the service account which was created for this purpose only.
> OIDC: Construct service account based on input

- actions/push-to-gar-docker/action.yaml
Adds `build-args` as an input argument, in case they are needed to build the image.
> `push-to-gar-docker` action: Add `build-args` when building the image

- actions/push-to-gar-docker/README.md
- actions/push-to-gar-docker/action.yaml
The name of the caller repo can be fetched from the `github` context. This PR replaces the `ROOT_REPO` env var, with `${{ github.repository }}`. Part of: https://github.com/grafana/shared-workflows/issues/30
> `push-to-gar-docker`: Remove ROOT_REPO, add github.repository from context

- actions/build-push-to-dockerhub/README.md
- actions/build-push-to-dockerhub/action.yaml
This follows the naming of the underlying Docker action and adds a "push" input so that users can control whether the image should be pushed or not.
> feat: Rename push-to-dockerhub-action

- actions/push-to-gar-docker/action.yaml
Since we are moving towards a pattern where each GAR repository should have its own prefix based on the format of the repository (docker, npm, rpm, deb), we need to make this change to make sure that the artifacts end up in the right registry.
> `push-to-gar-docker`: Add `docker-` prefix to image name

- actions/build-push-to-dockerhub/README.md
- actions/build-push-to-dockerhub/action.yaml
This also loads buildx and qemu if platforms are set.
> feat(build-push-to-dockerhub): Expose platforms parameter

- actions/build-push-to-dockerhub/action.yaml
- actions/dockerhub-login/README.md
- actions/dockerhub-login/action.yaml
To be used for workflows that don't use the same process as the `build-push-to-dockerhub` action
> Add `dockerhub-login` composite action

- actions/get-vault-secrets/action.yaml
- actions/trigger-argo-workflow/action.yaml
> chore: Update action dependencies

- .github/workflows/build-trigger-argo-workflow.yaml
- .github/workflows/publish-techdocs.yaml
- .github/workflows/test-get-vault-secrets.yaml
- README.md
- actions/build-push-to-dockerhub/action.yaml
- actions/dockerhub-login/action.yaml
- actions/get-vault-secrets/action.yaml
- actions/push-to-gar-docker/action.yaml
- actions/trigger-argo-workflow/action.yaml
This is following [security recommendations][hardening] from GitHub. For readability, We add a comment showing which tag the SHA refers to, as [Dependabot supports updating this when it makes PRs][update-comment].
[hardening]: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions
[update-comment]: https://github.blog/changelog/2022-10-31-dependabot-now-updates-comments-in-github-actions-workflows-referencing-action-versions/
> all: Always reference actions by commit SHA

- actions/build-push-to-dockerhub/action.yaml
- actions/push-to-gar-docker/action.yaml
This should fix the backward-compat issue reported in https://github.com/grafana/shared-workflows/pull/47
> fix: Make file argument optional in docker build actions

- actions/build-push-to-dockerhub/action.yaml
- actions/dockerhub-login/action.yaml
- actions/push-to-gar-docker/action.yaml
This should resolve NodeJS 16 deprecation warnings like this:
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7, docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a, docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
The version comments should now propery represent the commits.
> chore: Bump upstream docker actions

- actions/push-to-gar-docker/action.yaml
Replaces repository name with repository ID to fix issue created by: https://github.com/hashicorp/terraform-provider-google/issues/7443
> `push-to-gar-docker`: Replace `github.repository` with `github.repository_id`

- actions/lint-pr-title/README.md
The config file in the docs is missing the module.exports and makes the action to fail.
I am updating the docs to have the default example that works with the action.
> docs: update pr linter docs

- actions/build-push-to-dockerhub/README.md
- actions/build-push-to-dockerhub/action.yaml
- actions/push-to-gar-docker/README.md
Removed checkout step from `actions/build-push-to-dockerhub` to match convention with `push-to-gar-docker`, and to reduce complexity. Also updated docs for both actions to include inputs and (light) instruction for using dockerhub repos.
> Build-push-to-dockerhub: Remove checkout step

- actions/push-to-gar-docker/README.md
- actions/push-to-gar-docker/action.yaml
This PR is inspired by: 
- https://github.com/grafana/shared-workflows/tree/main/actions/build-push-to-dockerhub
It exposes the `platforms` parameter and will allow to make builds for multiple platforms/architectures.
> feat(build-push-to-gar): Expose platforms parameter

- actions/push-to-gar-docker/README.md
- actions/push-to-gar-docker/action.yaml
Adds caching options for container cache. Defaults to `type=gha` if no cache is provided.
> `push-to-gar-docker`: Add caching options

- actions/push-to-gar-docker/action.yaml
The way they were being validated was wrong. But we don't need a step to resolve them using a fallback value - we can achieve the same with `default` on the input instead.
> push-to-gar-docker: Fix cache inputs

- actions/push-to-gar-docker/README.md
- actions/push-to-gar-docker/action.yaml
Exposing the 3 outputs from [`docker/build-push-action`](https://github.com/docker/build-push-action?tab=readme-ov-file#outputs), as well as a few from [`docker/metadata-action`](https://github.com/docker/metadata-action?tab=readme-ov-file#outputs), for simpler downstream use.
> push-to-gar-docker: add outputs for ease-of-use

- .github/workflows/publish-techdocs.yaml
This option allows users to _not_ run `actions/checkout` of the current repo. This is useful in cases of generating docs in a previous workflow job.
> feat(pub-techdocs): add input for running `actions/checkout`

- actions/push-to-gar-docker/README.md
- actions/push-to-gar-docker/action.yaml
Adds `ssh` input as per: https://github.com/docker/build-push-action?tab=readme-ov-file#inputs
> `push-to-gar-docker`: Add `ssh` input

- .github/workflows/build-lint-pr.yml
- .github/workflows/build-trigger-argo-workflow.yaml
- .github/workflows/lint-shared-workflows.yaml
- .github/workflows/publish-techdocs.md
- .github/workflows/test-login-to-gar.yaml
- .prettierignore
- .prettierrc.yaml
- README.md
- actions/aws-auth/README.md
- actions/aws-auth/action.yaml
- actions/build-push-to-dockerhub/README.md
- actions/get-vault-secrets/README.md
- actions/lint-pr-title/README.md
- actions/lint-pr-title/action.yml
- actions/lint-pr-title/commitlint.config.js
- actions/lint-pr-title/index.js
- actions/login-to-gar/README.md
- actions/push-to-gar-docker/README.md
- actions/push-to-gar-docker/action.yaml
- actions/syft-sbom-report/README.md
- actions/syft-sbom-report/syft-sbom.yml
- actions/trigger-argo-workflow/README.md
I noticed when writing #107 that my editor wanted to rewrite some of the quotes in the file because they weren't following our `.editorconfig`'s style.
Fix all files according to `prettier` and then run prettier during pushes / pull requests so we don't regress. Add something to the README too, to make people aware of this.
> all: Fix according to editorconfig / markdownlint style

- actions/techdocs-rewrite-relative-links/main.go
- actions/techdocs-rewrite-relative-links/main_test.go
The idea is that something like `../README.md#hello` should be rewritten to `https://github.com/grafana/repo/README.md#hello`. Previously that didn't work as the filesystem lookups also included the hashname and so they always failed.
> techdocs-rewrite-relative-links: Handle links with hashnames properly

- actions/techdocs-rewrite-relative-links/README.md
- actions/techdocs-rewrite-relative-links/action.yaml
- actions/techdocs-rewrite-relative-links/main.go
The default log level is now "warn" and the rewriting process is not aborted if there is a file-lookup error.
> techdocs-rewrite-relative-links: Level levels and no abort on file error

- actions/techdocs-rewrite-relative-links/main.go
Previously the links were correct when entering and exiting the AST nodes. Doing that on exiting is enough :)
> techdocs-rewrite-relative-links: Only rewrite on leaving a link

- .github/workflows/lint-shared-workflows.yaml
- actions/techdocs-rewrite-relative-links/action.yaml
These have a schema, so we can check if they're correct beyond just being valid YAML. Use the JSON schema from schemastore.org to do this - so we have to convert the YAML files to JSON first. For this, we run in the `yq` container and use `yq`'s conversion feature.
~This is going to fail until #109 is merged~merged - works now
See [the run on the first commit in this PR][run] for an example of a failure.
[run]: https://github.com/grafana/shared-workflows/actions/runs/8923793469/job/24508781530?pr=110
> lint-shared-workflows: Also lint action definitions

- .github/workflows/publish-techdocs.yaml
- README.md
- actions/build-push-to-dockerhub/action.yaml
- actions/dockerhub-login/action.yaml
- actions/trigger-argo-workflow/action.yaml
Check the `shared-workflows` repo out and use a unique local path for all actions, instead of fetching `main`. This means that we are always internally compatible. Previously we would risk breaking backwards compatibility if someone had pinned a SHA, which is recommended.
We use a unique checkout path because `actions/checkout` removes the repository in a "post" step and we don't want to risk removing a checkout an "outer" action is using, in the case of nesting. Picture this scenario:
1. [outer] check shared-workflows out to `./_shared-workflows`
2. [nested] run a nested workflow which also checks shared-workflows out to the same path
3. [nested] do some work and then finish, running the "Post checkout" step to remove `./_shared-workflows`
4. [outer] try to do something in …
> build-push-to-dockerhub, dockerhub-login: Use local action

- .github/workflows/publish-techdocs.yaml
We already have it checked out under `publish-techdocs`, so use that.
> publish-techdocs: Fix the checkout path for `rewrite-relative-links`

- actions/trigger-argo-workflow/action.yaml
Fix installation path, to use the relative path specified during checkout.
> `trigger-argo-workflow`: Fix setup-go installation path

- actions/build-push-to-dockerhub/action.yaml
Skip logging in DockerHub if `inputs.push` is set to false.
Additionally, let the workflow fail early if run on any other event than `push` and `inputs.push` is set to true because of [what was discussed here](https://github.com/grafana/shared-workflows/pull/26#discussion_r1444280841) (TL;DR: we only want - at least for now - to only allow publishing to docker hub on push events).
I decided to fail instead of overriding silently the `push` to false input as it would be less confusing for user that may expect their image to be published. 
When it fails, this error is printed, which should help the action's users to understand why and how to move forward:
```
| Publishing to DockerHub is only allowed on push events.
| If you still want to build images without pushing them, set the push …
```
> chore: Skip log in to DockerHub when not publishing, fail if trying to publish on anything but `push` events

- actions/build-push-to-dockerhub/action.yaml
There's a truthiness problem here: inputs for composite actions are always strings, so `"false"` (which is the default) is evaluating to `true` for this conditional and we're logging into Docker Hub when we don't need to.
See [run with `main`][fail] with the default `push` value of `"false"`:
and [run with this branch][okay]
I was trying to type this as a review comment but I was too slow :grin: 
[fail]: https://github.com/grafana/wait-for-github/actions/runs/9076711847/job/24940103015#step:4:254
[okay]: https://github.com/grafana/wait-for-github/actions/runs/9076920608/job/24940688779#step:4:252
> build-push-to-dockerhub: Fix check for logging into Docker hub

- .github/workflows/publish-techdocs.yaml
For projects that submodule the GitHub wiki in docs, we need to set `submodules: true` on the checkout action.
> feat(pub-techdocs): checkout submodules

- .github/workflows/publish-techdocs.yaml
Workflow jobs run on separate runners and do not carry over the workspace. So, you can't generate docs in one job and then publish the generated docs in another.
> chore(pub-techdocs): remove `checkout-repo` option

- .github/workflows/publish-techdocs.md
- .github/workflows/publish-techdocs.yaml
This allows the user to pass in different options to `actions/checkout` submodules option. Default is `false`.
> feat(pub-techdocs): make checking out `submodules` configurable

- actions/aws-auth/README.md
- actions/aws-auth/action.yaml
We've got some cases where we want to look at the event name now, so add this to the claims from the token that get set as tags on our eventual (workload) IAM role.
> aws-auth: Add `event_name` to the claims passed by default

- .github/workflows/lint-shared-workflows.yaml
This is a required check - we need to make sure it runs for pull requests.
Checking out `${{ github.head_ref }}` from a fork doesn't work either, so dropthat from the `lint` action and use the default. The problem is that[`pull_request` workflows for forks run in the base repository][pr-base]. Inparticular, `${{ github.repository }}` is the base. So for this commit we weretrying to check out `iainlane/pr` from `grafana/shared-workflows`. But thatbranch is not on that repository because it's from a fork: it's on`iainlane/shared-workflows`.
There is a way to check out PRs from only the base repository though, by using `${{ github.ref }}`. For PRs that is something like `pull/140/merge`. In fact, using that is the default for `actions/checkout`, so we'll drop the setting of the `ref` input …
> lint-shared-workflows: Run for PRs

- actions/build-push-to-dockerhub/README.md
- actions/build-push-to-dockerhub/action.yaml
- Adds the following inputs which are needed to migrate [this Drone pipeline in `grafana/oncall`](https://github.com/grafana/oncall/blob/dev/.drone.yml#L129-L135):
- `build-args`
- `target`
- `cache-to`
- `cache-from`
- Modifies the action to allow `push`ing images to Dockerhub from all GitHub Actions event types **except `pull_request`** (previously the logic here was to _only_ allow `push`ing on a build triggered from a `push` event)
Closes https://github.com/grafana/shared-workflows/issues/80
> update inputs to `build-push-to-dockerhub` action

- .github/workflows/test-find-pr-for-commit.yml
- actions/find-pr-for-commit/README.md
- actions/find-pr-for-commit/action.yaml
Sometimes it's useful to be able to do things with a pull request after it gets merged. For example, maybe there's a build & deploy triggered on pushes to main and you want to report that back to the originating PR.
For that, you need to be able to go back from a commit to the PR that it came from. This simple action performs that lookup using GitHub's API. By default it will look up the current commit, so you can call the action with no inputs and it does the right thing in the common case. It also supports looking up other commits and working in other repositories, if a token is supplied.
A simple testsuite is also included to validate the workflow on changes.
> Add new action to find a PR for a commit

- .github/dependabot.yml
These are written in Go, and so we need to make sure that ecosystem is listed in `dependabot.yml` to keep their dependencies up to date.
> dependabot: Enable for `trigger-argo-workflow` and `techdocs-rewrite-relative-links`

- .github/workflows/codeql.yml
I've gone for doing this manually rather than through the GitHub UI. This is because when I enabled in the UI just now, there were some results in the generated code `actions/lint-pr-title/dist/index.js`, and these are better identified by security alerts on the dependencies, if there is an actual issue. We want to use CodeQL to find our own issues.
> CI: Enable CodeQL

- actions/build-push-to-dockerhub/README.md
- actions/push-to-gar-docker/README.md
These actions don't check the target repository out themselves, because the caller is likely to have done so already, and if they've changed anything before calling us then we would want that to be used for the build.
But we didn't document this in our examples, so do that.
> build-push-to-dockerhub, push-to-gar-docker: Document checkout step

- actions/build-push-to-dockerhub/README.md
- actions/build-push-to-dockerhub/action.yaml
We use the `gha` cache by default, and caches require using a different driver. We currently only enable `buildx` when `platforms` is given, as it is required for that type of build too. What we should do is always enable it.
Do that, and add an input to allow the driver to be specified. That is what `push-to-gar-docker` (the Artifact Registry companion of this Docker Hub action) does, and the more similar we can have those be the better.
> push-to-gar-docker: Always use buildx

- .github/publish-techdocs-testdata/docs/README.md
- .github/publish-techdocs-testdata/mkdocs.yml
- .github/workflows/publish-techdocs.yaml
- .github/workflows/test-publish-techdocs.yml
We don't need to get these from org secrets. Let's hardcode them.
If we can stop considering the bucket name a secret then we can remove the `secrets: inherit` requirement from our callers, which will be safer for them.
> publish-techdocs: Workload identity provider and SA email aren't secrets

- actions/get-vault-secrets/action.yaml
See [this `actions/runner` issue][issue]. The `${{ github.action_path }}` substitution we're using doesn't work properly when the action is run in a container job. The workaround folks are using is to use the `${GITHUB_ACTION_PATH}` _environment variable_ instead. We should start doing that too.
[issue]: https://github.com/actions/runner/issues/2185
> get-vault-secrets: Use env var to get action path rather than `github` context

- .github/workflows/publish-techdocs.md
- .github/workflows/publish-techdocs.yaml
The name of the bucket doesn't need to be a secret, so make it an input instead with a default.
Also, remove `inherit: secrets` from example, as no secrets are used in the workflow now.
> feat(pub-techdocs): make bucket an input

- .github/workflows/publish-techdocs.yaml
This change allows consumers of this workflow to specify the workload identity provider and service account for GCP auth.
Move current values to defaults.
https://github.com/grafana/shared-workflows/pull/165 is a prerequisite.
> chore(pub-techdocs): make workload id provider and SA inputs

- .github/workflows/lint-shared-workflows.yaml
Currently this action runs twice on a PR, because the triggers are `push` and `pull_request`. We need to be explicit to `push`, for the triggering to happen only when we push to main.
> `lint-shared-workflow`: Run action once, either on PR or push

- .github/actionlint.yaml
Upon testing [here](https://github.com/grafana/shared-workflows/actions/runs/9805007501/job/27073819964), I found that the lint fails if we don't specify the self-hosted runner names explicitly. 
Based on the error in that workflow, we need to create an actionlint.yaml file, which got generated when I ran:
`actionlint -init-config`. 
This list of labels will prevent this check from failing when we use our self-hosted runners.
We use the path.Match Glob syntax, as indicated [here](https://github.com/rhysd/actionlint/blob/main/docs/config.md).
> `lint-shared-workflows`: Add `actionlint.yaml`

- actions/push-to-gar-docker/action.yaml
There's no such thing as `create_credentials_file` input in `docker/metadata-action` - [link](https://github.com/docker/metadata-action?tab=readme-ov-file#inputs).
Fixes a warning in github actions.
> chore: remove `create_credentials_file` input

- .github/workflows/build-lint-pr.yml
- .github/workflows/build-trigger-argo-workflow.yaml
- .github/workflows/lint-shared-workflows.yaml
- .github/workflows/test-find-pr-for-commit.yml
- .github/workflows/test-get-vault-secrets.yaml
- .github/workflows/test-login-to-gar.yaml
- .github/workflows/test-publish-techdocs.yml
- .github/workflows/test-techdocs-rewrite-relative-links.yaml
Adding `merge_group` trigger to actions, now that we have enabled merge queues for this repository.
> ci: add merge_group trigger

- .github/workflows/test-find-pr-for-commit.yml
This action-testing workflow doesn't make sense when run in the merge group, since the commits there aren't associated with PRs any more. It's failing.
We could in the future consider doing work to get the association back, but I don't think we have a need for it right now, so we can stop running the check there instead.
> ci(test-find-pr-for-commit): don't run for merge group events

- actions/push-to-gar-docker/README.md
- actions/push-to-gar-docker/action.yaml
In the event that the GAR includes a repo name that differs from the GitHub repository name, `push-to-gar-docker` will fail to authenticate.
To correct this I'm adding an optional input that allows us to set a different repo name which is used to construct the GAR to authenticate to.
> fix: add repository_name input to push-to-gar-docker

- actions/push-to-gar-docker/README.md
- actions/push-to-gar-docker/action.yaml
Since [GAR doesn't support underscores in repository names][issue], we might as well do _something_ by default when we come across this situation. Here we replace them with `-`s.
The input added in 264a3f2a5d4f756715d5c1f3b37f627689e70ab1 can be used to override this behaviour.
[issue]: https://issuetracker.google.com/issues/229159012
> feat(push-to-gar-docker): replace underscores with hyphens in repo names

- actions/push-to-gar-docker/README.md
> fix(push-gar-doc): fix typo

- actions/generate-openapi-clients/README.md
- actions/generate-openapi-clients/action.yaml
This is for temporary workaround (which are unfortunately very common). These should generally not be committed, so they have to be run from within the composite action
> feat: modify openapi spec at client generation time

- .github/workflows/build-lint-pr.yml
- actions/lint-pr-title/package.json
Currently, if the author of a PR forgets to run `yarn build` to make sure the changes appear in `dist/index.js` there's no way to find this out in CI.
`build-lint-pr.yml` runs only for closed PRs which means that updates yarn after the fact.
It's better to have a check to know when we need to run `yarn build` locally before pushing. 
The action should now run for all changes in the `actions/lint-pr-title` or the workflow itself. Also, the previous logic will still work, for pull requests that come from `dependabot-npm` bot. When this case exists, a PR will be created after a dependabot is merged (as happens already)
**How this works?**
* One job does `yarn build`, and does a `git diff`. A `diff.txt` file is pushed as a job artifact.
* Another job which runs for PRs/push events if they …
> ci: make build-lint-pr-title action run on every pr

- actions/generate-openapi-clients/action.yaml
- actions/generate-openapi-clients/generate.sh
This makes importing the client easier
Currently: `github.com/grafana-com-public-clients/go` imports the `gcom` package so it's confusing. It's a go convention that the package name should match the dir name
This PR adds the package name to the generate path
> fix: generate go client in a subdir

- actions/setup-conftest/action.yaml
runner.os maps to `macOS`, the release artifact uses `Darwin` ...
> fix(setup-conftest): normalize runner.os

- actions/argo-lint/action.yaml
While attempting to use the `argo-lint` action in an action in another repository, the `github.action_repository` was empty. This smells like a bug that occurs when stacking composite actions from different repositories. I've filed a support issue with GitHub to have a look at this.
This action now falls back onto a hardcoded value.
> fix(argo-lint): fallback to hardcode action repo

- actions/setup-argo/action.yaml
Title says it, overlooked that in previous PR.
> fix(setup-argo): use amd64 as arch

- .github/workflows/test-setup-argo.yml
- actions/setup-argo/action.yaml
Should fix:
```
/home/runner/work/_temp/69566fd1-c0c9-4966-824c-63cf829358cd.sh: 2: [[: not found
```
and
```
gzip: /home/runner/work/incident/incident/bin/argo already exists;	not overwritten
```
Adds a testsuite to ensure that the cache is used when it should be, and that the `argo` binary is set up properly on the `PATH` and can be run.
> fix(setup-argo): use bash, fix idempotency, only restore if needed

- actions/aws-auth/action.yaml
The `workflow_ref` claim is currently unsupported by the upstream action and there are issues supporting this due to AWS limitations.
See https://github.com/catnekaise/cognito-idpool-auth/pull/9
> fix(aws-auth): use ref instead of workflow_ref claim

- .github/dependabot.yml
- .github/renovate-config.json
- .github/workflows/renovate.yml
Renovate supports updating actions versions in composite actions and Dependabot doesn't. That means in our `actions/*/action.yml` files we have a lot of out of date deps.
This is a test to see if it'll work for that case. We disable Dependabot for Actions and let Renovate manage them.
Check [logs for the run on this PR](https://github.com/grafana/shared-workflows/actions/runs/10903114856/job/30256479619?pr=240). They look good to me. If it works well after we merge this we could consider making this a shared workflow and putting the secrets in Vault rather than GH secrets, & then also whether we should enable for other dep types too.
> feat(deps): use Renovate to manage Actions dependencies

- .github/workflows/codeql.yml
- .github/workflows/renovate.yml
- actions/get-vault-secrets/action.yaml
When referencing actions, we'll do:
```yaml
uses: foo/bar-action@123456789 # v1.2.3
```
to reference by SHA but still say what the version was. Dependabot supports updating these comments when creating bumps, but Renovate doesn't do this when the comment points to the wrong version.
We had two cases of that in `codeql-action` and `vault-action`. Here we fix both.
Also, it's easier to test if we can kick off runs manually and if Renovate triggers when its config or workflow are changed, so add triggers for that.
[preset]: https://docs.renovatebot.com/presets-helpers/#helperspingithubactiondigeststosemver
> fix(renovate): fix action versions, add more triggers

- .github/workflows/lint-shared-workflows.yaml
Noticed this was warning in the Renovate logs. The only thing I can see
is that it should be `v4.3` not `v4.3.0`.
> fix(lint-shared-workflows): correct tag for `prettier_action`

- actions/trigger-argo-workflow/action.yaml
- actions/trigger-argo-workflow/cmd/trigger-argo-workflow/argo.go
- actions/trigger-argo-workflow/cmd/trigger-argo-workflow/main.go
- actions/trigger-argo-workflow/go.mod
We're migrating our Argo Workflows environment internally, and for that we currently have parallel deployments. We've namespaced the secrets needed to trigger in each cluster. This PR modifies to allow the new `dev-aws` instance and fetch the cluster-scoped secrets.
To save time for the production migration later, we'll also teach everything about `ops-aws` now, even though it doesn't exist yet.
> feat(trigger-argo-workflow): support {dev,ops}-aws instances and get repo-specifc paths

- .github/workflows/lint-pr-title.yml
- .github/workflows/lint-shared-workflows.yaml
We just merged `release-please` support in 023c802ae4fc29d9bc2b3428333a63f47a5dc255. The user this runs as is the default Actions bot user. One thing about this user in particular is that it doesn't trigger workflows to run. We can see that in #427 for example. At the time of writing no checks have run for that PR.
This means that its release PRs aren't actually mergeable, since we have a couple of required checks which come from Actions runs.
Fortunately we don't have to switch to an app. We can use the fact that the PRs are created in draft mode. To make a release, the process will be
1. Make PR ready for review.
2. Add PR to merge queue.
Workflows can be triggered by the `ready_for_review` activity type on the `pull_request` event. So they will be kicked off when a human does step 1.
> fix(ci): run required checks when undrafting PRs

- actions/lint-pr-title/action.yml
We give the step to set up `bun` a reference to the `package.json` file so that it can install the correct version. Unfortunately, we'd specified that incorrectly when the action is run locally (from this repo), so it [was not finding it][warning]. We need to give an absolute path.
[warning]: https://github.com/grafana/shared-workflows/actions/runs/11073509535/job/30770197846#step:3:14
> fix(lint-pr-title): correctly find the `package.json`

- actions/trigger-argo-workflow/cmd/trigger-argo-workflow/argo.go
We decided to have our temp domain on `grafana.net` to remove one variable (certificate) when cutting over.
> fix(trigger-argo-workflow): use correct url for ops on AWS

- actions/trigger-argo-workflow/cmd/trigger-argo-workflow/argo.go
Use the `grafana.net` domain for argo workflows dev instance as part of testing cut-over to aws
> fix(trigger-argo-workflow): use `argo-workflows-dev-aws.grafana.net` instead for dev-aws

- .github/workflows/publish-techdocs.md
- .github/workflows/publish-techdocs.yaml
Part of https://github.com/grafana/enghub/issues/405
Tested with https://github.com/grafana/enghub/actions/runs/11290282786/job/31401811080
Marked as breaking because it renames/changes some of the inputs as we need AWS-specific semantic here.
> feat(publish-techdocs)!: switch to AWS for publish techdocs

- .github/workflows/renovate.yml
We have Renovate app secrets in Vault now, and fetching secrets from there is our organisation's preferred way, so switch.
> chore(renovate): use secrets from Vault

- .github/workflows/test-get-vault-secrets.yaml
The `get-vault-secrets` action only works when run from a `grafana` repository, so skip this test if the PR is from a different repository. We will still get a run of this workflow for the change before merging, as we use merge queues. We can see an example of this failing in https://github.com/grafana/shared-workflows/pull/147.
I've created this PR itself from a fork, to test that this works. I pushed the same change to https://github.com/grafana/shared-workflows/pull/473 to see that we still ran the test from a non-fork. 👍
> fix(ci): only run get-vault-secrets ci from `grafana` PRs

- actions/get-vault-secrets/action.yaml
In 570898eda6d4fb6c0e4d45a24bf9681c89a12aa6 we renamed this but forgot to update a reference. `get-vault-secrets` is now failing.
> fix(get-vault-secrets): correct path to `translate-secrets`

- .github/workflows/build-trigger-argo-workflow.yaml
- .github/workflows/codeql.yml
- .github/workflows/renovate.yml
- .github/workflows/test-find-pr-for-commit.yml
- .github/workflows/test-get-vault-secrets.yaml
- .github/workflows/test-lint-pr-title.yml
- .github/workflows/test-login-to-gar.yaml
- .github/workflows/test-publish-techdocs.yml
- .github/workflows/test-setup-argo.yml
- .github/workflows/test-techdocs-rewrite-relative-links.yaml
We have the GitHub Actions bot user create release PRs, and this user doesn't trigger workflows. Fortunately, since we create the PRs in draft mode and a human undrafts to make a release, we can use this as a trigger to run workflows. This only works if the workflows trigger when undrafted. Add that here. This is the same approach we're taking in `wait-for-github` and it works fine there.
> chore(ci): run `pull_request` workflows when undrafting

- .github/workflows/publish-techdocs.yaml
- actions/aws-auth/action.yaml
Resolves https://github.com/grafana/shared-workflows/issues/483
This follows the same naming for local checkouts as the [techdocs-rewrite-relative-links](https://github.com/grafana/shared-workflows/tree/main/actions/techdocs-rewrite-relative-links) action. Follow-up to https://github.com/grafana/shared-workflows/commit/570898eda6d4fb6c0e4d45a24bf9681c89a12aa6
> fix(aws-auth): support checked out action mode

- actions/aws-auth/action.yaml
Currently when REPOSITORY_PATH is not provided I'm getting error: `./resolve-aws-region.sh: No such file or directory`.
Check: https://github.com/grafana/runner-images/actions/runs/11441826500/job/31838893119
This will cd into the action path from [context](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#github-context) in case `checkout-actions-repository-path` is not provided.
Related: #484
> fix(aws-auth): no such file for resolve-aws-region.sh

- actions/trigger-argo-workflow/action.yaml
- actions/trigger-argo-workflow/cmd/trigger-argo-workflow/argo.go
Now that we have migrated to `ops-eu-south-0`, remove references to the GCP cluster and allow for fetching the correct cluster-scoped secrets
> fix(trigger-argo-workflow): treat AWS ops instance as Argo Workflows ops

- .github/renovate-config.json5
Renovate pushes out new images most days, sometimes multiple times a day. We don't need to track these so closely, so let's look for these particular updates only once a week - early on Monday mornings.
> chore(renovate): update Renovate itself less frequently (weekly)

- .github/workflows/lint-shared-workflows.yaml
I noticed
> Could not determine new digest for update (github-tags package ludeeus/action-shellcheck)
in [a recent log][log]. This is because the tag is [`2.0.0`] and not `v2.0.0`.
[`2.0.0`]: https://github.com/ludeeus/action-shellcheck/releases/tag/2.0.0
[log]: https://github.com/grafana/shared-workflows/actions/runs/12050129862/job/33598355724#step:5:123
> fix(lint-shared-workflows): correct tag for shellcheck action

- README.md
- actions/argo-lint/README.md
- actions/aws-auth/README.md
- actions/build-push-to-dockerhub/README.md
- actions/dockerhub-login/README.md
- actions/generate-openapi-clients/README.md
- actions/get-vault-secrets/README.md
- actions/login-to-gar/README.md
- actions/login-to-gcs/README.md
- actions/push-to-gar-docker/README.md
- actions/push-to-gcs/README.md
- actions/send-slack-message/README.md
- actions/setup-argo/README.md
- actions/setup-conftest/README.md
- release-please-config.json
We need this feature so the README.md guide always contains the latest version of the action.
Currently our workflow READMEs are a bit misleading since we tell people to use `main`, which will cause backwards compatibility issues.
[Working example](https://github.com/grafana/shared-workflows/pull/571/files).
> chore: update readme when a new release is available

- .github/workflows/check-for-non-releasable-actions.yaml
- actions/syft-sbom-report/README.md
- actions/techdocs-rewrite-relative-links/README.md
- actions/trigger-argo-workflow/README.md
- actions/validate-policy-bot-config/README.md
- release-please-config.json
We need to ensure that all of our actions in this repositories are releasable. We are adding this check so when we create a new action it will fail if it cannot be released. 
Part of: https://github.com/grafana/shared-workflows/issues/574
Example of missing actions here: https://github.com/grafana/shared-workflows/actions/runs/12073279306/job/33669061564#step:6:29
Example of successful workflow after the missing actions have been added: https://github.com/grafana/shared-workflows/actions/runs/12073454603/job/33669584061#step:6:30
Example of successful workflow with cache enabled: https://github.com/grafana/shared-workflows/actions/runs/12082633004/job/33694117294
> feat: add workflow to check for non-releasable actions

- .github/workflows/publish-techdocs.yaml
This also saves the generated HTML as an artifact so that it can be more easily debugged.
> feat(publish-techdocs): add github-admonitions plugin

- actions/push-to-gar-docker/action.yaml
Uses login-to-gar action only on push events, to allow PRs that come from forks to at least be able to build docker images on PRs.
> fix: login to GAR only on push events

- actions/send-slack-message/README.md
- actions/send-slack-message/action.yaml
Update instructions based on: https://github.com/slackapi/slack-github-action/releases/tag/v2.0.0
> docs: update instructions after slack action v2 update

- actions/login-to-gcs/CHANGELOG.md
Fixes CHANGELOG - `costom-service-account` -> `service-account`
> chore: fix changelog for login-to-gcs action

- .github/workflows/release.yml
There's a failure on `main` ([workflow](https://github.com/grafana/shared-workflows/actions/runs/13008605692/job/36280983638)), when tagging major/minor versions.
This happens because the ref exists already and cannot be overridden. According to [GitHub's documentation](https://docs.github.com/en/rest/git/refs?apiVersion=2022-11-28#update-a-reference), we need `force: true` param to make this work.
> fix: force update existing tag when tagging major and minor versions

- .github/workflows/release.yml
Followup to: https://github.com/grafana/shared-workflows/pull/727.
See [github issue](https://github.com/octokit/rest.js/issues/339). `updateRef` and `getRef` need the short ref version of the reference, otherwise the ref cannot be found. [Working example](https://github.com/grafana/dsotirakis-test-repo/actions/runs/13017475327/job/36310097899).
> fix: use short ref version where needed

- actions/aws-auth/README.md
The README file in `aws-auth` action was wrongly pointing to `argo-lint` probably due to some bad c/p'ing. This PR updates the README.
> docs: fix wrong aws-auth reference in readme

- .github/workflows/check-drone-signature.yaml
Since this reusable workflow is used by OSS projects, we need to be aware if we're dealing with a fork or not, especially when it comes to PRs. If we're on a fork, we don't have access to the secret needed to run the drone ci config signature validation. In this case, we post a comment to the PR saying we're skipping the check and someone with proper repo persmissions needs to check/sign the drone ci config changes.
> feat(drone-sig): add check for fork

- .github/workflows/check-drone-signature.md
This change introduces documentation for the `check-drone-signature` reusable workflow. It gives an overview for what the purpose of the check is for and how to set up and use the workflow.
> docs(check-drone-sig): init doc for workflow

- actions/login-to-gar/action.yaml
We don't need to have one service account to check whether another service account exists or not. We can first try to authenticate using a service account, and if this fails then we can try authenticating with Direct WIF.
The flow:
* Workflow starts, and checks for the repo-specific service account:
* If it exists, it authenticates, prints the warning message and then logs in to GAR.
* If it doesn't exist, the authentication with a service account fails, but it won't fail the whole workflow (`continue-on-error = true`). Then it will jump to the Direct WIF bits, since the `access_token` won't exist.
Working examples:
* [Authenticate with a service account](https://github.com/grafana/dsotirakis-test-repo/actions/runs/13332044987/job/37238417455)
* [Authenticate with Direct …
> refactor: simplify login-to-gar, removes describe service account

- actions/login-to-gar/action.yaml
Our self-hosted runners and the github-hosted runners have the `gcloud` cli installed by default.
There are some cases though where a job runs from a container that doesn't have the gcloud installed this action will fail.
This PR installs the `gcloud` cli. Will be adding some caching in a next PR.
> fix: install gcloud in login-to-gar action

- README.md
- actions/argo-lint/action.yaml
- actions/build-push-to-dockerhub/README.md
- actions/build-push-to-dockerhub/action.yaml
- actions/dockerhub-login/action.yaml
- actions/generate-openapi-clients/README.md
- actions/lint-pr-title/README.md
- actions/push-to-gar-docker/README.md
- actions/push-to-gar-docker/action.yaml
- actions/push-to-gcs/README.md
- actions/push-to-gcs/action.yaml
- actions/techdocs-rewrite-relative-links/README.md
- actions/techdocs-rewrite-relative-links/action.yaml
- actions/trigger-argo-workflow/action.yaml
- actions/validate-policy-bot-config/README.md
Reduces the possibility of inadvertently leaking the credentials in consuming workflows.
This has the potential to break workflows that rely on the persisted credentials and I haven't checked which ones may be likely to break
Signed-off-by: Jack Baldry <jack.baldry@grafana.com>
> fix: ensure every action disables git credential persistence

- actions/login-to-gar/action.yaml
Adds `--verbosity=error` to the `gcloud auth configure-docker` command.
**Without the flag:**
```
$ gcloud auth configure-docker us-docker.pkg.dev
WARNING: Your config file at [/Users/dimitris/.docker/config.json] contains these credential helper entries:
{
"credHelpers": {
"asia.gcr.io": "gcloud",
"eu.gcr.io": "gcloud",
"gcr.io": "gcloud",
"marketplace.gcr.io": "gcloud",
"staging-k8s.gcr.io": "gcloud",
"us-docker.pkg.dev": "gcloud",
"us.gcr.io": "gcloud"
}
}
Adding credentials for: us-docker.pkg.dev
gcloud credential helpers already registered correctly.
```
**With the verbosity flag:**
```
$ gcloud auth configure-docker --verbosity error us-docker.pkg.dev
Adding credentials for: us-docker.pkg.dev
gcloud credential helpers already registered correctly.
```
> ci: make configure-docker less verbose

- actions/trigger-argo-workflow/action.yaml
If a repository has a `go.work` setup then doing `go run` in a subfolder that is not part of the workspace fails.
> fix(trigger-argo-workflows): support repos using Go workspaces

- actions/get-vault-secrets/action.yaml
- added a new input `export_env` to set the [exportEnv](https://github.com/hashicorp/vault-action?tab=readme-ov-file#exportenv) input of hashicorp/vault-action
- default behavior is unchanged (defaults to `true`).
Closes #518.
> feat: expose exportEnv in get-vault-secrets

- actions/push-to-gar-docker/action.yaml
Due to [decommissioned cache service brownouts](https://github.blog/changelog/2025-03-20-notification-of-upcoming-breaking-changes-in-github-actions/#decommissioned-cache-service-brownouts), we need to update and pin the buildx version (see comment [here](https://github.com/docker/build-push-action/issues/1345#issuecomment-2770572479)) to prevent our actions from failing. 
Working example:
https://github.com/grafana/website/actions/runs/14350268712/job/40227545764?pr=25031#step:21:1
> fix: update buildx version to `latest`

- actions/push-to-gar-docker/README.md
- actions/push-to-gar-docker/action.yaml
Expose the underlying `target` input from docker's [build-push-action](https://github.com/docker/build-push-action/blob/master/action.yml#L104)
> feat(push-to-gar-docker): add target input for multi-stage builds

- README.md
- actions/push-to-gar-docker/action.yaml
- actions/push-to-gcs/action.yaml
When CI jobs are running git status after using `push-to-gar-docker` or `push-to-gcs` actions, the checked out `shared-workflows` directory appears. This breaks some CI check workflows, where the expectation is that there's not going to be any diff after certain operations (like building npm, or linting etc.). 
This PR ensures that at the end of each the above two actions, the directory will be cleaned up.
> ci: don't persist shared workflows folder after action is done

- actions/lint-pr-title/src/index.ts
Previously, main was also executed during testing, which led to unexpectedly failed tests. This change prevents main from being run unless it's also the entrypoint.
> fix(lint-pr-title): do not run main on import

- actions/login-to-gar/action.yaml
Stop persisting credentials for `login-to-gar` action, in the case where it uses Direct WIF for authentication.
Credentials are no longer needed since the step uses an `auth_token`.
**NOTE**: We cannot do this for authentication steps that use service accounts, since the credential files are needed for this operation. `login-to-gar` will soon stop using service accounts (unless pinned).
[Working example](https://github.com/grafana/dsotirakis-test-repo/actions/runs/14613561911/workflow).
> ci: stop persisting credentials in google auth steps

- actions/login-to-gar/action.yaml
Partially: https://github.com/grafana/shared-workflows/issues/919
**NOTE**: `create_credentials_file: false` is now removed, since credentials file is needed for the command to work.
Will create followup PRs to remove the credentials at the end of the action.
[Working example](https://github.com/grafana/dsotirakis-test-repo/actions/runs/14620901664/job/41068472662).
> feat: use `docker-credential-gcr` instead of `auth_token` for `login-to-gar` action

- actions/get-vault-secrets/README.md
- actions/get-vault-secrets/action.yaml
The option to set export_env to false was given, but there was no way to retrieve the secrets when that was set.
> fix(get-vault-secrets): add outputs for export_env false

- .github/workflows/README.md
- .github/workflows/reusable-zizmor.md
- .github/workflows/reusable-zizmor.yml
- .github/workflows/self-zizmor.yml
- .markdownlint.json
- README.md
_This depends on #930._
This is a [reusable workflow] which runs the [`zizmor`][zizmor] static analysis tool on a repo's GitHub Actions workflow files. This will report things such as whether there is potential for untrusted code to be injected via a template. See a full list of checks in [the documentation][zizmor-checks].
This workflow will run zizmor, upload results to GitHub's code scanning service (requires an Advanced Security subscription for private repositories), and comment on the pull request with the results. The comment will be re-posted on each run - and previous comments hidden - so the most recent comment will always show the current results.
[reusable workflow]: https://docs.github.com/en/actions/using-workflows/reusing-workflows
[zizmor]: …
> feat(zizmor): add a reusable workflow for zizmor GitHub Actions static analysis

- .github/renovate-config.json5
- .github/workflows/reusable-zizmor.yml
The variable needs to be named `..._VERSION` for the `# renovate:` comment to work.
Additionally, a fix is needed in the regex used for such comments. It currently matches too much in YAML files, so lines _after_ the version are caught and this breaks the logic. Fortunately, the same fix had been implemented internally for the same reason, so we can copy it here.
> fix(zizmor): fix check for new versions

- .github/workflows/renovate.yml
- .github/workflows/reusable-zizmor.yml
- .github/workflows/test-find-pr-for-commit.yml
- .github/workflows/test-login-to-gar.yaml
This PR is from a fork!
See the commit tab for details of these fixes:
- **ci(reusable-zizmor): fix when run from a fork and there are findings**
- **ci(test-login-to-gar): don't run for forks**
- **ci(renovete): fix workflow runs from forks, run in merge queue**
- **ci(test-find-pr-for-commit): don't run for forks**
> fix: workflow runs from forks

- .github/workflows/reusable-zizmor.md
- .github/workflows/reusable-zizmor.yml
Ensure that zizmor can always run, even if Advanced Security is not enabled in a specific repository.
This change forces the workflow to continue even if the upload fails
> fix(zizmor): try code scanning by default

- .github/workflows/reusable-zizmor.md
- .github/workflows/reusable-zizmor.yml
If the target repo hasn't got its own config file, we'll use our defaults. In this way we can provide defaults for our users but let them be overridden.
Note that this is inline in the CI job itself. I don't think that's ideal but I didn't find a better way to do this. It doesn't seem possible for reusable workflows to find out their own ref, which is what they'd need to do to get a sibling file from their repo.
I've made a support ticket with GitHub about that. If they give me a fix I'll implement that.
> feat(zizmor): use a default config file

- actions/login-to-gar/action.yaml
- actions/login-to-gcs/action.yaml
- actions/push-to-gar-docker/README.md
- actions/push-to-gar-docker/action.yaml
- actions/push-to-gcs/README.md
- actions/push-to-gcs/action.yaml
Resolves: https://github.com/grafana/shared-workflows/issues/919
What happens is that actions that run after the reusable actions which produce gcp credentials, are being left "dirty" since the credentials are persisted in the runner.
We are introducing a new step which actually removes the credentials instantly when the composite action runs, and doesn't have to wait until the post run steps. This way we can ensure that credentials won't be left on the runner without purpose. The user has to know whether they'll still need the credentials after the composite action finishes, and change the `delete_credentials_file` boolean variable accordingly.
For `push-to-*` actions in this repo, we have to make sure that the credentials file won't be deleted after the `login-to-*` action, since the …
> ci: remove gcp credentials after composite action finishes

- .github/workflows/reusable-zizmor.yml
Use the pre-built zizmor wheel to avoid building the binary on the first run.
If we see a future where we want to build the Zizmor binary from a commit hash instead of a pre-built wheel it's probably easier to close this PR and continue to use the Rust toolchain.
> perf: use prebuilt zizmor wheel

- .github/workflows/publish-techdocs.md
We have required `id-token: write` for a while, but not documented it.
> docs(publish-techdocs): document permissions

- .github/workflows/test-remove-checkout-credentials.yaml
- actions/remove-checkout-credentials/README.md
- actions/remove-checkout-credentials/action.yaml
- catalog-info.yaml
This action can be used to clean up Git credentials after an `actions/checkout` call in case `persist-credentials: false` is not an option.
> feat: adding new remove-checkout-credentials-action

- actions/login-to-gar/README.md
Adds inputs description in `login-to-gar` action.
> docs: add inputs section in login-to-gar action

- .github/workflows/reusable-zizmor.md
- .github/workflows/reusable-zizmor.yml
- .github/workflows/self-zizmor.yml
- .github/zizmor.yml
We've got a TODO item saying that storing the config in the YAML definition of the reusable workflow itself isn't the best. It's hard to find, edit, and there's no linting since it's considered a string and not YAML itself.
It's not super obvious how to do this, though. What we want to do is use a file which is alongside the workflow. So if we're called like:
```yaml
job:
zizmor:
uses: grafana/shared-workflows/.github/workflows/reusable-zizmor.yml@abc123
```
...the correct thing to do is to use the file from `abc123` and not anything else which might be incompatible or change independently of the caller updating their pointer to us.
GitHub doesn't give us a checkout of the reusable workflow. So we need to fetch the file from GitHub ourselves. What we need to do that is the ref (`abc123`). …
> feat(reusable-zizmor): store default config file separately

- .github/workflows/reusable-zizmor.md
- .github/workflows/reusable-zizmor.yml
- .github/workflows/self-zizmor.yml
- .github/workflows/test-zizmor-offline.yml
In our more popular repositories, we're seeing that the per-repo limit of 15,000 API calls are being hit rather quickly now that zizmor is enabled across everywhere. This enables the action to be configured in a way that will not hit the GitHub API (which does reduce the number of things that the binary will pickup). This should reduce the number of failures that we're seeing in those repositories.
After this change, GitHub tokens should now be used via an `extra-args` parameter of `--gh-token` which will be passed into zizmor
> feat(zizmor): enable running offline only

- .github/workflows/reusable-zizmor.md
- .github/workflows/reusable-zizmor.yml
Forks can't get an ID token. We use this method to look up the version we're called at: get an OIDC ID token and then use the `job_workflow_ref` claim. We're currently hard failing when this doesn't work, which means we throw an error for runs from forks.
We do this whole ID token dance to find our current ref, so we can fetch the org-wide config. This is important but it's not _critical_ - not enough to fail the run. It would be better to succeed by falling back to using the default config from _upstream_.
> fix(reusable-zizmor): fix runs from forks

- actions/aws-auth/README.md
- actions/build-push-to-dockerhub/README.md
- actions/dockerhub-login/README.md
- actions/find-pr-for-commit/README.md
- actions/generate-openapi-clients/README.md
- actions/login-to-gar/README.md
- actions/login-to-gcs/README.md
- actions/push-to-gar-docker/README.md
- actions/push-to-gcs/README.md
- actions/remove-checkout-credentials/README.md
- actions/setup-argo/README.md
- actions/setup-conftest/README.md
- actions/setup-jrsonnet/README.md
- actions/validate-policy-bot-config/README.md
Moved permissions block from top-level to job-level for each action's example workflow in their readme's.
The same work as defined #955.
> docs(multiple-actions): move permissions to job level in workflows

- catalog-info.yaml
- scripts/generate-catalog-info/go.mod
- scripts/generate-catalog-info/go.sum
- scripts/generate-catalog-info/main.go
This should make collisions with similarly named actions in other repositories more unlikely.
> chore: add repository name as prefix to actions in the catalog

- actions/send-slack-message/README.md
- actions/send-slack-message/action.yaml
This pull request includes updates to the `actions/send-slack-message` GitHub Action to refine documentation and input descriptions. The most important changes include updating a link in the README, correcting formatting in the inputs table, and simplifying the description of the `payload` input.
* [`actions/send-slack-message/README.md`](diffhunk://#diff-bc36534e8c270f109c38c4bf0352ca7c49e571ced409855c162eca3977d23ee1L6-R6): Updated the link to the Slack GitHub Action documentation to point to the latest and more specific URL for sending data using the Slack API method.
* [`actions/send-slack-message/README.md`](diffhunk://#diff-bc36534e8c270f109c38c4bf0352ca7c49e571ced409855c162eca3977d23ee1L100-R101): Fixed the formatting of the inputs table by aligning column headers and descriptions. …
> docs(send-slack-notification): remove outdated docs, url update

- .github/workflows/reusable-zizmor.yml
We're finding that some forks of code cannot pull the content from this repo's zizmor config. We should ensure that zizmor runs with the default configuration if there is no configuration provided
> fix: only use zizmor config if it exists

- actions/get-vault-secrets/README.md
This pull request updates the `actions/get-vault-secrets/README.md` file to provide a more accurate and helpful link for Grafana Labs engineers regarding Vault instructions and best practices.
* Documentation update:
* Updated the internal documentation link to point to the correct section on Vault instructions and best practices for storing secrets in CI workflows. (`actions/get-vault-secrets/README.md`)
Dependent on https://github.com/grafana/deployment_tools/pull/266757 for the new link to work.
> docs(get-vault-secrets): update enghub link to point to new vault docs

- actions/login-to-gar/action.yaml
Replacing the [upstream action](https://github.com/StevenACoffman/setup-docker-credential-gcr) so we can install the binary for different architectures, as well as removing sudo from the "untar" process. (will create a PR to the upstream repo, at least for the architectures - will leave the sudo handling to the author by creating an issue).
Note that we create a new directory under `/opt/` so it can be accessible from within a docker image, in case an action runs inside a container.
Part of: https://github.com/grafana/shared-workflows/issues/980
> fix: use custom step for docker-credential-gcr

- actions/build-push-to-dockerhub/action.yaml
Update the `build-push-to-dockerhub` to utilize Grafana's internal docker mirror for self-hosted runners.
Enhancements to Docker Buildx setup:
* Introduced a conditional `buildkitd-config` parameter to specify the BuildKit daemon configuration file when running in a self-hosted environment.
This requires https://github.com/grafana/deployment_tools/pull/269388 to be merged first.
Part of https://github.com/grafana/deployment_tools/issues/269366
> feat(build-push-to-dockerhub): enable docker mirror for buildx on self-hosted runners

- actions/push-to-gar-docker/action.yaml
Update the `push-to-gar-docker` to utilize Grafana's internal docker mirror for self-hosted runners.
Key change:
* [`actions/push-to-gar-docker/action.yaml`](diffhunk://#diff-cd7255ed249c21034dc35c5e4e4db93b4cc690ce2c0f7d4034e1be574484a8feR174): Added a conditional expression to set the `buildkitd-config` parameter to `/etc/buildkitd.toml` when the runner is self-hosted, and an empty string otherwise. This improves compatibility with self-hosted environments.
This requires https://github.com/grafana/deployment_tools/pull/269388 to be merged first.
Part of https://github.com/grafana/deployment_tools/issues/269366
> feat(push-to-gar-docker): enable docker mirror for buildx on self-hosted runners

- release-please-config.json
See issue for more information https://github.com/grafana/shared-workflows/issues/981 
Dependabot and Renovate seem to follow a "namespaced" solution when it comes to tagging versions in monorepos. We should try to follow that to make automated updates smoother.
Note that changes won't happen to tags until new changes are made to the actions themselves
--------
Have made the exact same field addition in another private repo of mine, and created two new versions:
Then I used the test-action in a random workflow tagged as `test-action/v1.1.10` and ran dependabot manually.
This returns:
Along with a PR to update the actual dependency.
--------
* [Git Documentation](https://git-scm.com/docs/git-check-ref-format#_description)
* Convo w/ GitHub support:
```
Now lets see how Dependabot handles …
```
> build: replace tag separator `/` (slash) with `-` (hyphen)

- .github/workflows/lint-shared-workflows.yaml
`Validate action definitions` step is failing on every PR.
By running:
```bash
curl \
--verbose \
--retry 5 \
--remote-time \
--remote-name \
--time-cond github-action.json \
--etag-save github-action.json-etag \
--etag-compare github-action.json-etag \
https://json.schemastore.org/github-action.json
```
and trying to `cat` the result `github-actions.json` file, I got:
```bash
<head><title>Document Moved</title></head>
<body><h1>Object Moved</h1>This document may be found <a HREF="https://www.schemastore.org/github-action.json">here</a></body>%   
```
This PR makes this change.
> fix: change url of the github-action.json

- .github/workflows/test-login-to-gar.yaml
- actions/login-to-gar/README.md
- actions/login-to-gar/action.yaml
Removes old deprecated authentication after all GAR ops have moved to Direct WIF.
Part of: https://github.com/issues/assigned?issue=grafana%7Cdeployment_tools%7C259653
> feat!: only allow direct workload identity federation in login-to-gar

- actions/login-to-gar/action.yaml
After https://github.com/grafana/shared-workflows/pull/1009, there was a condition which checked for credentials path and the actual input flag which was accidentally removed. This PR adds it back.
> fix(login-to-gar): check if delete_credentials_file is set

- actions/get-latest-workflow-artifact/README.md
- actions/get-latest-workflow-artifact/src/main.ts
In some situations a workflow might get triggered that depends on an artifact while the producing workflow is still in-progress.
There might even be the case that the artifact hasn't been uploaded yet and so this scenario also allows for 5 retries taking place.
The action now also returns the status of the used workflow as output.
> feat(get-latest-workflow-artifact): consider in-progress runs

- .github/workflows/renovate.yml
In c0944351c68e107649cb9c9a86204b400b607564 we fixed the Renovate job to be skipped for PRs from forks. But at the same time we broke non-fork runs. The `if` condition was looking for `github.event.pull_request`, and of course that's not set for any other event.
Fix it so that we always run for non-PR events. The `on:` conditions take care of us there.
> fix(renovate): fix runs from non-forks

- actions/aws-auth/action.yaml
This is a workaround for https://github.com/actions/runner/issues/716 (closed but not fixed): use `${GITHUB_ACTION_PATH}` instead of `${{ github.action_path }}`.
> fix(aws-auth): fix reference to the action's own path

- .github/workflows/renovate.yml
We've currently re-running Renovate for _any_ run in the merge group, which is making it push branches whenever anything is queued to be merged. This is causing way too many runs and unnecessary rebases and CI runs. We should only run in write mode on a schedule, on an explicit manual request, or from the main branch if Renovate's config itself changes
> fix(renovate): use a dry-run when run from the merge group

- .github/workflows/reusable-zizmor.yml
- .github/workflows/test-get-vault-secrets.yaml
- .github/workflows/test-login-to-gar.yaml
- actions/build-push-to-dockerhub/README.md
- actions/build-push-to-dockerhub/action.yaml
- actions/login-to-gcs/action.yaml
- actions/push-to-gar-docker/README.md
- actions/push-to-gar-docker/action.yaml
- actions/push-to-gcs/action.yaml
The current version of Zizmor finds some potential template injection issues. We can fix these by indirecting via the `env`, or in a couple of cases by adding ignore comments where we can't really fix the issue.
Something happened to break our config discovery. What we do is download a default config file from this repo, write it to a temporary file, set that file's path as `ZIZMOR_CONFIG`, and then pass this as `--config` if it's set. Possibly as the result of a version bump, Zizmor started handling `ZIZMOR_CONFIG` differently. An empty string here is treated as a file to search for, which doesn't work, and so we get errors.
A fix for this last one is to use a different variable name that doesn't collide with the one Zizmor itself is using. Rename to `ZIZMOR_CONFIG_PATH` accordingly. …
> fix: remediate latest zizmor findings, fix supplying zizmor config

- actions/trigger-argo-workflow/cmd/trigger-argo-workflow/argo.go
- actions/trigger-argo-workflow/cmd/trigger-argo-workflow/main.go
- actions/trigger-argo-workflow/cmd/trigger-argo-workflow/main_test.go
- actions/trigger-argo-workflow/go.mod
- actions/trigger-argo-workflow/go.sum
Besides the "normal" updates this also moves the "submit" command into a proper subcommand which is necessary because otherwise the extraArgs would interfere with the rest of the argument parsing. Despite that, this change should not
be breaking since the `submit` command was also necessary in the previous implementation.
> chore(trigger-argo-workflow): use cli/v3

- actions/build-push-to-dockerhub/action.yaml
As suggested in, https://github.com/grafana/shared-workflows/pull/1190#issuecomment-3154115009, adds the same support for load to the build-push-to-dockerhub workflow variation.
> feat(build-push-to-dockerhub): support load parameter

- actions/go-flaky-tests/CHANGELOG.md
- actions/go-flaky-tests/README.md
- actions/go-flaky-tests/action.yaml
- actions/go-flaky-tests/cmd/go-flaky-tests/analyzer.go
- actions/go-flaky-tests/cmd/go-flaky-tests/config.go
- actions/go-flaky-tests/cmd/go-flaky-tests/git.go
- actions/go-flaky-tests/cmd/go-flaky-tests/main_test.go
- actions/go-flaky-tests/cmd/go-flaky-tests/testdata/complex_scenario.json
- actions/go-flaky-tests/cmd/go-flaky-tests/testdata/single_test_scenario.json
- actions/go-flaky-tests/run-local.sh
Extends the basic flaky test detection in https://github.com/grafana/shared-workflows/pull/1013 with Git history analysis to identify recent authors of flaky tests. This enables better ownership tracking and more targeted notifications when tests become flaky.
- **Git Integration**: New `GitClient` interface and implementation for repository operations
- **Author Detection**: Uses `git log -L` to find recent commits that modified specific test functions
- **Test File Discovery**: Locates test files in the repository using grep patterns
- **Enriched Reports**: Flaky test reports now include commit history and author information
- `git.go`: Git operations implementation with proper error handling
- Enhanced `analyzer.go`: Now calls Git functions to gather author information
- Updated action …
> feat: add git history analysis to go flaky tests

- .github/renovate-config.json5
Disable major version updates for .NET in the Renovate config.
https://github.com/grafana/shared-workflows/pull/1305#pullrequestreview-3189208284
> chore: disable major version updates for .NET SDK

- .github/workflows/pre-commit.yaml
Currently, `release-please` PRs (and other PRs triggered by bots) are getting blocked by certain checks that aren't getting triggered, namely `pre-commit`, which lacks a `ready_for_review` pull request trigger type, meaning it never gets ran on bot PRs, as the other trigger types don't get activated. This PR should resolve that.
<details><summary>Old description</summary>
#1036 is currently stuck on some CI jobs as a result of CodeQL, pre-commit, and Zizmor not working when the PR author is `github-actions[bot]`. This PR allows them to be skipped in that case, but adds `policy-bot` to enforce that.
One question is if any work needs to be done to apply the same restrictions laid out in [this part of our terraform config for this repository](https://github.com/grafana/deployment_tools/blob/6 …
> fix(ci): add `ready_for_review` type to pull request triggers for `pre-commit` workflow

- actions/cleanup-branches/README.md
- actions/cleanup-branches/action.yml
Add a new action that will delete branches that meet the following requirements:
1. Not the `head` ref of an open PR.
2. Not a protected branch.
3. `HEAD` commit created before `max-date`.
Some things I wanted to achieve with this where I feel like other community actions fall short:
1. Avoid using the GitHub API where `git` is sufficient.
2. Avoid unnecessary third party dependencies.
> feat: add cleanup-branches action

- actions/go-flaky-tests/action.yaml
- actions/go-flaky-tests/cmd/go-flaky-tests/analyzer.go
- actions/go-flaky-tests/cmd/go-flaky-tests/config.go
- actions/go-flaky-tests/run-local.sh
Adds ability to exclude specific tests from flaky test analysis by name. Tests in the ignored list are filtered out before applying top-K limit, ensuring they don't consume analysis slots or generate GitHub issues.
continued from https://github.com/grafana/shared-workflows/pull/1276
this is the last piece in go-flaky-tests. I don't plan to work more on this apart from bug fixes or PR reviews
> feat(go-flaky-tests): add ignored-tests option to filter out specific test failures
